### ISSUE TITLE
Scanner Installation

### ISSUE THREAD

**Issue by SKazemi89** [SICKAG/sick_safetyscanners#108]
Hi,

I used Ubuntu 20.04 and ROS neotic.
I want to install the microscann3 via binaries or source, but via binaries says: Unable to locate package and via source says couldent connect to server.
I think this must be somewhere in Ubuntu or Brower (I test with firefox and Chrome) must be a firewall or a proxy.
maybe you can tell me how can I fix the problem here ?
thanks a lot

**Comment by puck-fzi** [comment]
Sounds like your device is not properly connected to the internet.
This sounds like a rather specific problem for installations, I guess you can't install other packages either.

Sadly I can't really help you there. It sounds like you need to setup your network correctly, since github and the sources should be reachable.
