### ISSUE TITLE
Costmap dynamic obstacle is not updated.

### ISSUE THREAD

**Issue by XieWup** [SICKAG/sick_safetyscanners#113]
Hi, When we used sicknanoscan3 and pedestrians walking on the costmap, the obstacles in the cost map cannot be cleared in time, leaving a shadow track.
But if we use another radar(RPLIDAR S1), it OK
nacoscan3 topic:
![643809cf67df8f04d091e602a2f83ea](https://user-images.githubusercontent.com/89019094/208036444-9ee54b47-c4a7-4bc9-8a29-7e1a32ee447f.png)

RPLIDAR S1 topic:
![019c2fb9bb69b2597a370205c4ea871](https://user-images.githubusercontent.com/89019094/208036130-176eb682-c043-4924-ac75-1e6534c16f6d.png)

Is it caused by angle_increment or other parameters?

**Comment by puck-fzi** [comment]
Hi, this might be dependent on the node which creates your costmap. The topics of the two sensors will differ in their parameters. This might led to slightly different behavior in the creation. It might be just that the frequencies of both topics differ. Without further information it is hard to determine exactly what the problem is. However I don't think its a driver related problem. So maybe you can get better help at https://answers.ros.org/

**Comment by XieWup** [comment]
Thank you for your reply. You are right. This is not caused by radar
