### ISSUE TITLE
Monitoring Case Switching over Ethernet/IP 

### ISSUE THREAD

**Issue by yemreikiz** [SICKAG/sick_safetyscanners#21]
Is it possible to send a case switching command or is there a way to send information to the **Assemblies**(such as assembly 105 or 130) for external communication using **CoLa2** or any other way? My setup is `microScan3 Pro`, connected to my computer over the Ethernet via `FX3GEPR Gateway` and `FX3CPU0` with `FX3-MPL0` plug.

**Comment by puck-fzi** [comment]
Hi yemreikiz,
as far as I know this is not possible since the assemblies are part of the safety setup of the microscan. CoLa2 is mainly used to read data and variables from the sensor and invoke methods such as where to send the udp packages. But it is not meant to change the safety configuration of the sensor.
