### ISSUE TITLE
Redundant information in MeasurementDataMsg.msg?

### ISSUE THREAD

**Issue by NikolasE** [SICKAG/sick_safetyscanners#36]
Is there a case in which len(scan_points) != number_of_beams?

**Comment by puck-fzi** [comment]
It should not be different as I understand. But it is given like that from the sensor itself and therefore piped out in the Raw Sensor Data. This data is not in any form interpreted in the driver ans simply all fields from the UDP pakets are parsed and send as a ROS Msg.

But it appears that it actually might be different, since there is a issue around these fields. See Issue:
https://github.com/SICKAG/sick_safetyscanners/issues/32
