### ISSUE TITLE
Why does the RawMicroScanDataMsg not include a frame_id?

### ISSUE THREAD

**Issue by NikolasE** [SICKAG/sick_safetyscanners#37]
Maybe I just missed it, but does the RawMicroScanDataMsg contain the frame_id of the scanner? It's quite surprising to have a 'header'-field that is no std_msgs/Header.

**Comment by puck-fzi** [comment]
I agree the header field might be a bit misleading. Maybe that should be changed.

And the general idea for the RawMicroScanDataMsg was, that this pipes out the data as it is given by the laserscanner itself as a ROS Msg. Therefore the frame id is not set there, since this is a ROS specific parameter and not in the raw sensor data.
