### ISSUE TITLE
Change launch file "host_ip" to "target_ip"

### ISSUE THREAD

**Issue by tbohnma** [SICKAG/sick_safetyscanners#75]
Hello, 

the default launch file stated here:

- https://github.com/SICKAG/sick_safetyscanners/blob/master/launch/sick_safetyscanners.launch

contains following parameter:

- host_ip
- host_udp_port

In relation to the naming in safety designer, they should be renamed to 

- target_ip
- target_upd_port

![image](https://user-images.githubusercontent.com/33319087/106592299-a0d3f800-654f-11eb-9411-2db35a9aa00c.png)

This is not only to follow a more structured naming convention, but also to state more clear that this option is not about who is hosting ROS, but who should receive the data. 
Especially when using the broadcast function (https://github.com/SICKAG/sick_safetyscanners/issues/27) this leads to user errors, since users type in their own computers ip, but not the broadcast IP address.

**Comment by puck-fzi** [comment]
Hi, I agree that the new naming convention might be a bit better suited, however the host should be the one getting the data to process. Therefore, one could argue that the its the host of the driver. 
But I prefer your proposed naming scheme. Since this will introduce breaking changes in the ROS API I will integrate it in a later stage into the drive. Together with a deprecation warning for the host parameters.
Thanks for your input.
